name: rezepte
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Ubuntu
      fonts:
        - asset: fonts/ubuntu/Ubuntu-Bold.ttf
          weight: 700
        - asset: fonts/ubuntu/Ubuntu-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/ubuntu/Ubuntu-Italic.ttf
          style: italic        
        - asset: fonts/ubuntu/Ubuntu-Light.ttf
          weight: 300
        - asset: fonts/ubuntu/Ubuntu-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/ubuntu/Ubuntu-Medium.ttf
          weight: 500
        - asset: fonts/ubuntu/Ubuntu-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/ubuntu/Ubuntu-Regular.ttf
          weight: 400