name: rezepte
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  fonts:
    - family: Ubuntu
      fonts:
        - asset: fonts/ubuntu/Ubuntu-Bold.ttf
          weight: 700
        - asset: fonts/ubuntu/Ubuntu-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/ubuntu/Ubuntu-Italic.ttf
          style: italic        
        - asset: fonts/ubuntu/Ubuntu-Light.ttf
          weight: 300
        - asset: fonts/ubuntu/Ubuntu-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/ubuntu/Ubuntu-Medium.ttf
          weight: 500
        - asset: fonts/ubuntu/Ubuntu-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/ubuntu/Ubuntu-Regular.ttf
          weight: 400